### ISSUE TITLE
NotifyCompleteUploads is not working when enabling NotifyCreatedUploads

### ISSUE THREAD

**Issue by dhiemaz** [tus/tusd#442]
I have setup tusd UnrouteHandler in my code using below configuration : 
```
handler, err = tusd.NewUnroutedHandler(tusd.Config{
		BasePath:              "/files/",
		StoreComposer:         composer,
		NotifyTerminatedUploads: false,
		NotifyUploadProgress:    false,
		NotifyCreatedUploads:    true,
		NotifyCompleteUploads: true,
	})
```

in my go routine I catch all the event especially for those which I have enable
```
go func() {
		select {
		case event := <-routedHandler.CompleteUploads:
			fmt.Printf("Upload %s finished, Metadata : %v", event.Upload.ID, event.Upload.MetaData)
			close(routedHandler.CompleteUploads)
		case event := <-routedHandler.TerminatedUploads:
			fmt.Printf("Upload %s terminated, Metadata : %v", event.Upload.ID, event.Upload.MetaData)
			close(routedHandler.TerminatedUploads)
		case event := <-routedHandler.UploadProgress:
			fmt.Printf("Upload %s is in progress, Offset : %v", event.Upload.ID, event.Upload.Offset)
			close(routedHandler.UploadProgress)
		case event := <-routedHandler.CreatedUploads:
			fmt.Printf("Upload %s started, Metadata : %v", event.Upload.ID, event.Upload.MetaData)
			close(handler.CreatedUploads)
		}
}()
```

but when I start uploading the file, it seems hookEvent `CompleteUploads` is not triggered, but when only `NotifyCompleteUploads` set true, the hookEvent `CompleteUploads` run just fine.

**Comment by Acconut** [comment]
You must not close the notification channels. tusd expects them to be open and if you close them, tusd will hang since it cannot send messages on a closed channel. Removing all the calls to `close` should solve the problem for you.

**Comment by Acconut** [comment]
Another thing that just came to my mind is that you need a for loop in your goroutine which fetches the events from the channels. Your code right now just waits for the first event and then stops looking for new events.

**Comment by dhiemaz** [comment]
I have remove close channel, but the issue still happens. 

here is the looping code for fetching event.

```
go func() {
		for {
			select {
			case event := <-handler.CompleteUploads:
					logger.WithFields(logger.Fields{"component": "handler", "action": "upload video"}).
						Infof("video successfully uploaded : video-id=%d, filename=%s", vid, newFilename)
				}
			case event := <-handler.TerminatedUploads:
				logger.WithFields(logger.Fields{"component": "handler", "action": "upload video"}).
					Infof("upload terminated : %v", event)
			case event := <-handler.UploadProgress:
				logger.WithFields(logger.Fields{"component": "handler", "action": "upload video"}).
					Infof("upload progress : %v", event)
			case event := <-handler.CreatedUploads:
				logger.WithFields(logger.Fields{"component": "handler", "action": "upload video"}).
					Infof("create upload : %v", event)
			}
		}
	}()
```

**Comment by Acconut** [comment]
That look's better! Please share tusd's log output. Maybe there is some information in it.

Can you explain more what you mean with:

> but when I start uploading the file, it seems hookEvent CompleteUploads is not triggered, but when only NotifyCompleteUploads set true, the hookEvent CompleteUploads run just fine.

**Comment by digitalplaywright** [comment]
@dhiemaz The "/" in the end of the path supplied to the API is significant, and I believe you have to create separate go-routines with listeners to the channels. If you drop it then the CompleteUploads hook won't be called.

Example client:
```golang
package main

import (
    "os"
    tus "github.com/eventials/go-tus"
)

func main() {
    f, err := os.Open("my-file.txt")

    if err != nil {
        panic(err)
    }

    defer f.Close()

    // create the tus client.
    client, _ := tus.NewClient("http://localhost:8080/files/", nil)

    // create an upload from a file.
    upload, _ := tus.NewUploadFromFile(f)

    // create the uploader.
    uploader, _ := client.CreateUpload(upload)

    // start the uploading process.
    uploader.Upload()
}
```

With this server

```golang
package main

import (
	"fmt"
	"net/http"

	"github.com/tus/tusd/pkg/filestore"
	tusd "github.com/tus/tusd/pkg/handler"
)

func main() {
	// Create a new FileStore instance which is responsible for
	// storing the uploaded file on disk in the specified directory.
	// This path _must_ exist before tusd will store uploads in it.
	// If you want to save them on a different medium, for example
	// a remote FTP server, you can implement your own storage backend
	// by implementing the tusd.DataStore interface.
	store := filestore.FileStore{
		Path: "./uploads",
	}

	// A storage backend for tusd may consist of multiple different parts which
	// handle upload creation, locking, termination and so on. The composer is a
	// place where all those separated pieces are joined together. In this example
	// we only use the file store but you may plug in multiple.
	composer := tusd.NewStoreComposer()
	store.UseIn(composer)

	// Create a new HTTP handler for the tusd server by providing a configuration.
	// The StoreComposer property must be set to allow the handler to function.
	handler, err := tusd.NewHandler(tusd.Config{
		BasePath:              "/files/",
		StoreComposer:         composer,
		NotifyTerminatedUploads: false,
		NotifyUploadProgress:    true,
		NotifyCreatedUploads:    false,
		NotifyCompleteUploads: true,

	})
	if err != nil {
		panic(fmt.Errorf("Unable to create handler: %s", err))
	}

	// Start another goroutine for receiving events from the handler whenever
	// an upload is completed. The event will contains details about the upload
	// itself and the relevant HTTP request.
	go func() {
		for {
			event := <-handler.CompleteUploads
			fmt.Printf("Upload %s finished\n", event.Upload.ID)
		}
	}()

	go func() {
		for {
			event := <-handler.UploadProgress
			fmt.Printf("UploadProgress %s finished\n", event.Upload.ID)
		}
	}()


	// Right now, nothing has happened since we need to start the HTTP server on
	// our own. In the end, tusd will start listening on and accept request at
	// http://localhost:8080/files
	http.Handle("/files/", http.StripPrefix("/files/", handler))
	err = http.ListenAndServe(":8080", nil)
	if err != nil {
		panic(fmt.Errorf("Unable to listen: %s", err))
	}
}
```
