### ISSUE TITLE
Wrong error if path doesn't exists

### ISSUE THREAD

**Issue by alexandrevicenzi** [tus/tusd#98]
If I set a path that doesn't exists for `FileStore` when I send a POST request I get an error:

```
HTTP/1.1 404 Not Found
Content-Length: 17
Content-Type: text/plain; charset=utf-8
Tus-Resumable: 1.0.0
X-Content-Type-Options: nosniff
Date: Wed, 25 Jan 2017 18:14:57 GMT

upload not found
```

upload not found made me think that was a programming error with my program, but it was just a missing upload folder.

If the folder exists but tusd has no permission the error is a little bit better:

```
HTTP/1.1 500 Internal Server Error
Content-Length: 78
Content-Type: text/plain; charset=utf-8
Tus-Resumable: 1.0.0
X-Content-Type-Options: nosniff
Date: Wed, 25 Jan 2017 18:16:26 GMT

open /uploads/e4007fe2716488ae4b1c9889db1fa708.bin: permission denied
```

It would be nice to report a better error, or at least log somewhere.

This was the log:

```
[tusd] event="RequestIncoming" method="POST" path=""
[tusd] event="ResponseOutgoing" status="404" method="POST" path="" error="upload not found"
[tusd] event="RequestIncoming" method="POST" path=""
[tusd] event="ResponseOutgoing" status="404" method="POST" path="" error="upload not found"
[tusd] event="RequestIncoming" method="POST" path=""
[tusd] event="ResponseOutgoing" status="404" method="POST" path="" error="upload not found"
```

No error on logs 😢

**Comment by Acconut** [comment]
Thank you for reporting. The reason for this behavior is that tusd interprets all error which arise from missing files/directories as if the upload was not found. However, this should be fixed with this patch.

**Comment by zvictor** [comment]
the same happens in case you are uploading to Google Storage and you forgot to create the bucket

**Comment by Acconut** [comment]
@zvictor Would you mind creating a new issue with details on how to produce your specific problem?

**Comment by zvictor** [comment]
there you go: #241

Thanks for the help and all the great work done so far in this project! 🎉

**Comment by Acconut** [comment]
Thank you, it's always nice to get positive feedback :)
